/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  VsotMain as VsotMain
} from './components/vsot-main/vsot-main';

declare global {
  interface HTMLVsotMainElement extends VsotMain, HTMLElement {
  }
  var HTMLVsotMainElement: {
    prototype: HTMLVsotMainElement;
    new (): HTMLVsotMainElement;
  };
  interface HTMLElementTagNameMap {
    "vsot-main": HTMLVsotMainElement;
  }
  interface ElementTagNameMap {
    "vsot-main": HTMLVsotMainElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "vsot-main": JSXElements.VsotMainAttributes;
    }
  }
  namespace JSXElements {
    export interface VsotMainAttributes extends HTMLAttributes {
      
    }
  }
}

